<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0"/>
        <PackageReference Include="MudBlazor" Version="8.15.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Components\Form\Designer.razor" />
      <UpToDateCheckInput Remove="Components\Form\DynamicForm.razor" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Components\Form\TextField.cs">
        <DependentUpon>TextFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\AutoCompleteField.cs">
        <DependentUpon>AutoCompleteFieldRenderer.razor</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
