<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="9.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
        <PackageReference Include="MudBlazor" Version="9.0.0" />
        <PackageReference Include="Tizzani.MudBlazor.HtmlEditor" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Components\Form\Designer.razor" />
      <UpToDateCheckInput Remove="Components\Form\DynamicForm.razor" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Components\Form\TextField.cs">
        <DependentUpon>TextFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\SelectField.cs">
        <DependentUpon>SelectFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\CheckBoxField.cs">
        <DependentUpon>CheckBoxFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\ColorPickerField.cs">
        <DependentUpon>ColorPickerFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\DatePickerField.cs">
        <DependentUpon>DatePickerFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\EmailField.cs">
        <DependentUpon>EmailFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\FileUploadField.cs">
        <DependentUpon>FileUploadFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\NumericField.cs">
        <DependentUpon>NumericFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\PasswordField.cs">
        <DependentUpon>PasswordFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\RadioButtonField.cs">
        <DependentUpon>RadioButtonFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\IconSelectionField.cs">
        <DependentUpon>IconSelectionFieldRenderer.razor</DependentUpon>
      </Compile>
      <Compile Update="Components\Form\HtmlEditorField.cs">
        <DependentUpon>HtmlEditorFieldRenderer.razor</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Content Update="Components\Form\IconSelectionSettingsRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\ColumnSpanSizeRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\IconSelectionDialog.razor">
        <DependentUpon>IconSelectionFieldRenderer.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\AddNewFieldDialog.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\ColorPickerSettingsRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\DataSourceSettingsRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\DependsOnRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\RuleSettingsRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\DatePickerFormatTypeSettingsRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
      <Content Update="Components\Form\DatePickerHourFormatTypeSettingsRenderer.razor">
        <DependentUpon>FormFieldProperties.razor</DependentUpon>
      </Content>
    </ItemGroup>

</Project>
