<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <Title>DotBoil.TemplateEngine</Title>
	  <Authors>Ömer Faruk Şahin</Authors>
	  <Description>The DotBoil.TemplateEngine package is built on the DotBoil project. It simplifies Razor Syntax Engine integration.</Description>
	  <PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RazorLight" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
  </ItemGroup>

</Project>
