<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <Title>DotBoil.Validator</Title>
	  <Authors>Ömer Faruk Şahin</Authors>
	  <Description>The DotBoil.Validator package is built on the DotBoil project. It simplifies FluentValidation integration.</Description>
	  <PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
  </ItemGroup>

</Project>
