<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <Title>DotBoil.Validator</Title>
	  <Authors>Ömer Faruk Şahin</Authors>
	  <Description>The DotBoil.Validator package is built on the DotBoil project. It simplifies FluentValidation integration.</Description>
	  <PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
	  <Version>1.0.2</Version>
	  <PackageIcon>dotboil.png</PackageIcon>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icons\dotboil.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Link>dotboil.png</Link>
    </None>
  </ItemGroup>

</Project>
