<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DotBoil.AuthGuard.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\SamplePage\Page1.cshtml" />
    <_ContentIncludedByDefault Remove="Views\SamplePage\Page2.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotBoil.AuthGuard.Application\DotBoil.AuthGuard.Application.csproj" />
    <ProjectReference Include="..\DotBoil.UserConsents\DotBoil.UserConsents.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
