<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Title>DotBoil.Cors</Title>
		<Authors>Ömer Faruk Şahin</Authors>
		<Description>Configurable CORS policy management for DotBoil applications. Define allowed origins, headers, and methods through appsettings.json without writing manual middleware setup code.</Description>
		<PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
		<Version>1.9.3</Version>
		<PackageIcon>dotboil.png</PackageIcon>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DotBoil\DotBoil.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\..\icons\dotboil.png">
	    <Pack>True</Pack>
	    <PackagePath></PackagePath>
	    <Link>dotboil.png</Link>
	  </None>
	</ItemGroup>

</Project>
