<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <Title>DotBoil.MassTransit</Title>
	  <Authors>Ömer Faruk Şahin</Authors>
	  <Description>The DotBoil.MassTransit package is built on the DotBoil project. It simplifies MassTransit integration.</Description>
	  <PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
	  <Version>1.0.2</Version>
	  <PackageIcon>dotboil.png</PackageIcon>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.0.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.1" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icons\dotboil.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Link>dotboil.png</Link>
    </None>
  </ItemGroup>

</Project>
