<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DotBoil.Parameter</Title>
    <Authors>Ömer Faruk Şahin</Authors>
    <Description>Runtime application parameter management for DotBoil. Stores named key-value parameters in a MySQL database with Redis caching, enabling typed read/write access to configuration values without application restarts.</Description>
    <PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
    <Version>1.1.0</Version>
    <PackageIcon>dotboil.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.1" />
	  <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icons\dotboil.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Link>dotboil.png</Link>
    </None>
  </ItemGroup>

</Project>
