<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>disable</Nullable>
	  <Title>DotBoil.EntityFrameworkCore</Title>
	  <Authors>Ömer Faruk Şahin</Authors>
	  <Description>Entity Framework Core integration for DotBoil applications. Manages DbContext registration, multi-database provider support (MySQL, SQL Server), automated migrations, and a generic repository pattern.</Description>
	  <PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
	  <Version>1.9.4</Version>
	  <PackageIcon>dotboil.png</PackageIcon>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\icons\dotboil.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Link>dotboil.png</Link>
    </None>
  </ItemGroup>

</Project>
