<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Layout\MainLayout.razor" />
      <_ContentIncludedByDefault Remove="Components\Layout\NavMenu.razor" />
      <_ContentIncludedByDefault Remove="Components\Layout\ReconnectModal.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Counter.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Error.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Home.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\NotFound.razor" />
      <_ContentIncludedByDefault Remove="Components\Pages\Weather.razor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DotBoil.Studio.Core\DotBoil.Studio.Core.csproj" />
      <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
    </ItemGroup>

</Project>
