<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>DotBoil.AuthGuard</PackageId>
        <Title>DotBoil.AuthGuard</Title>
        <Authors>Ömer Faruk Şahin</Authors>
        <Description>The DotBoil.AuthGuard package is built on the DotBoil project. It simplifies login and user authorization integration.</Description>
        <PackageProjectUrl>https://github.com/ofaruksahin/DotBoil</PackageProjectUrl>
        <RepositoryUrl>https://github.com/ofaruksahin/DotBoil</RepositoryUrl>
        <Version>1.0.2</Version>
        <PackageIcon>dotboil.png</PackageIcon>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DotBoil.Caching\DotBoil.Caching.csproj" />
      <ProjectReference Include="..\DotBoil.Cors\DotBoil.Cors.csproj" />
      <ProjectReference Include="..\DotBoil.EFCore\DotBoil.EFCore.csproj" />
      <ProjectReference Include="..\DotBoil.Localization\DotBoil.Localization.csproj" />
      <ProjectReference Include="..\DotBoil.Logging\DotBoil.Logging.csproj" />
      <ProjectReference Include="..\DotBoil.Mapper\DotBoil.Mapper.csproj" />
      <ProjectReference Include="..\DotBoil.MassTransit\DotBoil.MassTransit.csproj" />
      <ProjectReference Include="..\DotBoil.Mediator\DotBoil.Mediator.csproj" />
      <ProjectReference Include="..\DotBoil.Parameter\DotBoil.Parameter.csproj" />
      <ProjectReference Include="..\DotBoil.Validator\DotBoil.Validator.csproj" />
      <ProjectReference Include="..\DotBoil\DotBoil.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
      <PackageReference Include="NETCore.Encrypt" Version="2.1.1" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\icons\dotboil.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
        <Link>dotboil.png</Link>
      </None>
    </ItemGroup>

</Project>
